#!/bin/sh
# Start/stop the ProofWeb Server.
#

CHROOTDIR=/chroot

CMDLINE="-coqtop /coq/bin/coqtop.opt -localhost prover.cs.ru.nl -port 82 -address 0.0.0.0"

test -f ${CHROOTDIR}/webserve || exit 0

. /lib/lsb/init-functions

ulimit -n 1048576

case "$1" in
start)	log_begin_msg "Starting ProofWeb Server ..."
        start-stop-daemon --start -q -N 10 -p ${CHROOTDIR}/webserve.pid -n webserve -r ${CHROOTDIR} -a /webserve -- $CMDLINE
        log_end_msg $?
	;;
stop)	log_begin_msg "Stopping ProofWeb Server ..."
        start-stop-daemon --stop  -q -p ${CHROOTDIR}/webserve.pid -n webserve
        rm -f ${CHROOTDIR}/webserve.pid
        log_end_msg $?
        ;;
restart) log_begin_msg "Restarting ProofWeb Server ..."
        start-stop-daemon --stop  -R 5 -q -p ${CHROOTDIR}/webserve.pid -n webserve
        rm -f ${CHROOTDIR}/webserve.pid
        start-stop-daemon --start -q -N 10 -p ${CHROOTDIR}/webserve.pid -n webserve -r ${CHROOTDIR} -a /webserve -- $CMDLINE
        log_end_msg $?
        ;;
*)	log_success_msg "Usage: /etc/init.d/proofweb start|stop|restart"
        exit 1 
        ;;
esac
exit 0
